### ISSUE TITLE
Cannot install package from today?

### ISSUE THREAD

**Issue by AugustT** [goldingn/versions#5]
The function `install.versions` is failing to install leaflet:

``` r
> install.versions(pkgs = 'leaflet', versions = '1.0.0')
Error in download.file(url, file, quiet = TRUE) : 
  cannot open URL 'https://mran.revolutionanalytics.com/snapshot/2016-02-16/src/contrib/Archive/leaflet'
```

The function did work for a number of packages. I note that the date in the URL is today's date and wonder if that is part of the problem?

I also wonder if this function could be improved by holding the errors until it has tried to install all packages? Currently this error stops the installation of all packages in my call to `install.versions`.

**Comment by goldingn** [comment]
Hmmm...

`leaflet` does not appear to be listed on [MRAN](https://mran.revolutionanalytics.com/snapshot/2016-02-16/src/contrib/Archive/) or [CRAN](https://cran.rstudio.com/src/contrib/Archive/). Probably because it has never been updated (added to CRAN at version 1.0.0 in 2014 and not touched since).

You get the same error with `versions`: 

``` r
install.versions('versions', '0.1')
```

```
curl: (22) The requested URL returned error: 404 Not Found
 Error in url.lines(url) : 
  URL does not appear to exist: https://mran.revolutionanalytics.com/snapshot/2016-02-16/src/contrib/Archive/versions
```

I think something must have changed with the structure of CRAN as I'm pretty sure I tried these out before...

**Comment by goldingn** [comment]
This now works for me:

``` r
devtools::install_github('goldingn/versions')
library('versions')
install.versions(pkgs = 'leaflet', versions = '1.0.0')
```

Need to update on CRAN next. Well spotted!
